In [1]:
# Import libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import  seaborn as sns

In [3]:
# Control display of seaborn data -optional
pd.options.display.max_columns=50
sns.set(style="darkgrid", rc={"axes.facecolor":"#CAF1DE"})

In [4]:
# Loading dataset
df = pd.read_csv('bse_dataset.csv')
df

,Timestamp,What is your gender?,Age,What is your emotion?,Year of birth,What is your CGPA?,Do you have a Girl Friend or BOY Friend,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you have seek any specialist for a treatment?
0,05/07/2023 09:38:39,Male,21,Content,2002,4.22,No,No,Yes,Yes,Yes
1,05/07/2023 09:38:57,Marabou stock,45,Weird,2100,8.9,Yes,Yes,Yes,Yes,No
2,05/07/2023 09:39:09,Female,20,Happy,2002,3.98,No,No,Yes,Yes,No
3,05/07/2023 09:39:12,Male,21,Happy,2003,4.37,No,No,No,No,Nope
4,05/07/2023 09:39:14,Female,21,Happy,2002,3.63,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...
92,05/07/2023 09:53:56,Female,68,Sad,1953,4.8,No,Yes,Yes,Yes,Yes
93,05/07/2023 09:54:13,Male,29,Hopeful,1994,I don't know yet,"Sure, multiple girlfriends",No,No,No,No
94,05/07/2023 09:54:28,Male,22,Fighting poverty,2001,3.12,Girl friends are thieves,Yes,Yes,No,No
95,05/07/2023 09:54:36,Male,23,good and bad,2000,3.5,Namiiro Zahara Bidin,No,No,No,No
96,05/07/2023 09:54:52,male,30,hunger,2023,5,ARI,no,yeah,nah,yeah

In [5]:
# Analysis workflow
# Understanding the dataset preparation
# Data cleaning- wrong data format, null values
# Explorator data analysis
#insight data visualition

In [6]:
# Understanding the data structure
# checking the shape of the data
df.shape

(97, 11)

In [7]:
# column name
df.columns

Index(['Timestamp', 'What is your gender?', 'Age', 'What is your emotion?',
       'Year of birth', 'What is your CGPA?',
       'Do you have a Girl Friend or BOY Friend', 'Do you have Depression?',
       'Do you have Anxiety?', 'Do you have Panic attack?',
       'Did you have seek any specialist for a treatment? '],
      dtype='object')

In [8]:
# Check for basic information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 11 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   Timestamp                                           97 non-null     object
 1   What is your gender?                                97 non-null     object
 2   Age                                                 97 non-null     int64
 3   What is your emotion?                               96 non-null     object
 4   Year of birth                                       97 non-null     object
 5   What is your CGPA?                                  97 non-null     object
 6   Do you have a Girl Friend or BOY Friend             97 non-null     object
 7   Do you have Depression?                             97 non-null     object
 8   Do you have Anxiety?                                97 non-null     object
 9   Do you have Panic attack?                           97 non-null     object
 10  Did you have seek any specialist for a treatment?   97 non-null     object
dtypes: int64(1), object(10)
memory usage: 8.5+ KB

In [9]:
# Data cleaning
df2 = pd.read_csv("bse_dataset2.csv")
df2

,Timestamp,What is your gender?,Age,What is your emotion?,Year of birth,What is your CGPA?,Do you have a Girl Friend or BOY Friend,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you have seek any specialist for a treatment?
0,05/07/2023 09:38:39,Male,21.0,Content,2002,4.22,No,No,Yes,Yes,Yes
1,05/07/2023 09:38:57,Marabou stock,45.0,Weird,2100,8.9,Yes,Yes,Yes,Yes,No
2,05/07/2023 09:39:09,Female,20.0,Happy,2002,3.98,No,No,Yes,Yes,No
3,05/07/2023 09:39:12,Male,21.0,Happy,2003,4.37,No,No,No,No,Nope
4,05/07/2023 09:39:14,Female,21.0,Happy,2002,3.63,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...
97,05/07/2023 09:56:37,Female,29.0,Grateful,2002,3.6,No,No,No,No,Nope
98,05/07/2023 09:59:18,Female,21.0,Grateful,31/12/2001,2.88,Yes,No,Yes,No,No
99,05/07/2023 10:11:02,Male,21.0,Yes,2002,3.2,No,Yes,Yes,No,No
100,05/07/2023 10:17:36,Female,21.0,Sad,2002,5,Yes,Yes,No,No,No
101,05/07/2023 10:47:51,Male,21.0,Sad,2002,4.6,Yes,Yes,Yes,Yes,No

In [10]:
# check for unique values
for i in df2.columns:
    print(i, "--", df2[i].unique(), "-------", df2[i].unique())

Timestamp -- ['05/07/2023 09:38:39' '05/07/2023 09:38:57' '05/07/2023 09:39:09'
 '05/07/2023 09:39:12' '05/07/2023 09:39:14' '05/07/2023 09:39:20'
 '05/07/2023 09:39:21' '05/07/2023 09:39:23' '05/07/2023 09:39:26'
 '05/07/2023 09:39:27' '05/07/2023 09:39:28' '05/07/2023 09:39:33'
 '05/07/2023 09:39:38' '05/07/2023 09:39:40' '05/07/2023 09:39:45'
 '05/07/2023 09:39:46' '05/07/2023 09:39:47' '05/07/2023 09:39:49'
 '05/07/2023 09:39:50' '05/07/2023 09:39:54' '05/07/2023 09:39:56'
 '05/07/2023 09:40:00' '05/07/2023 09:40:01' '05/07/2023 09:40:02'
 '05/07/2023 09:40:08' '05/07/2023 09:40:10' '05/07/2023 09:40:12'
 '05/07/2023 09:40:13' '05/07/2023 09:40:16' '05/07/2023 09:40:25'
 '05/07/2023 09:40:26' '05/07/2023 09:40:27' '05/07/2023 09:40:33'
 '05/07/2023 09:40:34' '05/07/2023 09:40:40' '05/07/2023 09:40:42'
 '05/07/2023 09:40:46' '05/07/2023 09:40:47' '05/07/2023 09:40:54'
 '05/07/2023 09:40:59' '05/07/2023 09:41:00' '05/07/2023 09:41:01'
 '05/07/2023 09:41:05' '05/07/2023 09:41:06' '05/07/2023 09:41:07'
 '05/07/2023 09:41:08' '05/07/2023 09:41:11' '05/07/2023 09:41:18'
 '05/07/2023 09:41:19' '05/07/2023 09:41:20' '05/07/2023 09:41:25'
 '05/07/2023 09:41:30' '05/07/2023 09:41:31' '05/07/2023 09:41:33'
 '05/07/2023 09:41:35' '05/07/2023 09:41:36' '05/07/2023 09:41:40'
 '05/07/2023 09:41:41' '05/07/2023 09:41:42' '05/07/2023 09:41:47'
 '05/07/2023 09:41:56' '05/07/2023 09:41:58' '05/07/2023 09:42:04'
 '05/07/2023 09:42:15' '05/07/2023 09:42:17' '05/07/2023 09:42:39'
 '05/07/2023 09:42:48' '05/07/2023 09:43:05' '05/07/2023 09:43:08'
 '05/07/2023 09:43:22' '05/07/2023 09:43:36' '05/07/2023 09:43:56'
 '05/07/2023 09:44:09' '05/07/2023 09:44:14' '05/07/2023 09:44:15'
 '05/07/2023 09:44:35' '05/07/2023 09:45:13' '05/07/2023 09:45:38'
 '05/07/2023 09:45:40' '05/07/2023 09:49:52' '05/07/2023 09:51:39'
 '05/07/2023 09:51:52' '05/07/2023 09:52:27' '05/07/2023 09:52:57'
 '05/07/2023 09:53:52' '05/07/2023 09:53:56' '05/07/2023 09:54:13'
 '05/07/2023 09:54:28' '05/07/2023 09:54:36' '05/07/2023 09:54:52'
 '05/07/2023 09:56:37' '05/07/2023 09:59:18' '05/07/2023 10:11:02'
 '05/07/2023 10:17:36' '05/07/2023 10:47:51'] ------- ['05/07/2023 09:38:39' '05/07/2023 09:38:57' '05/07/2023 09:39:09'
 '05/07/2023 09:39:12' '05/07/2023 09:39:14' '05/07/2023 09:39:20'
 '05/07/2023 09:39:21' '05/07/2023 09:39:23' '05/07/2023 09:39:26'
 '05/07/2023 09:39:27' '05/07/2023 09:39:28' '05/07/2023 09:39:33'
 '05/07/2023 09:39:38' '05/07/2023 09:39:40' '05/07/2023 09:39:45'
 '05/07/2023 09:39:46' '05/07/2023 09:39:47' '05/07/2023 09:39:49'
 '05/07/2023 09:39:50' '05/07/2023 09:39:54' '05/07/2023 09:39:56'
 '05/07/2023 09:40:00' '05/07/2023 09:40:01' '05/07/2023 09:40:02'
 '05/07/2023 09:40:08' '05/07/2023 09:40:10' '05/07/2023 09:40:12'
 '05/07/2023 09:40:13' '05/07/2023 09:40:16' '05/07/2023 09:40:25'
 '05/07/2023 09:40:26' '05/07/2023 09:40:27' '05/07/2023 09:40:33'
 '05/07/2023 09:40:34' '05/07/2023 09:40:40' '05/07/2023 09:40:42'
 '05/07/2023 09:40:46' '05/07/2023 09:40:47' '05/07/2023 09:40:54'
 '05/07/2023 09:40:59' '05/07/2023 09:41:00' '05/07/2023 09:41:01'
 '05/07/2023 09:41:05' '05/07/2023 09:41:06' '05/07/2023 09:41:07'
 '05/07/2023 09:41:08' '05/07/2023 09:41:11' '05/07/2023 09:41:18'
 '05/07/2023 09:41:19' '05/07/2023 09:41:20' '05/07/2023 09:41:25'
 '05/07/2023 09:41:30' '05/07/2023 09:41:31' '05/07/2023 09:41:33'
 '05/07/2023 09:41:35' '05/07/2023 09:41:36' '05/07/2023 09:41:40'
 '05/07/2023 09:41:41' '05/07/2023 09:41:42' '05/07/2023 09:41:47'
 '05/07/2023 09:41:56' '05/07/2023 09:41:58' '05/07/2023 09:42:04'
 '05/07/2023 09:42:15' '05/07/2023 09:42:17' '05/07/2023 09:42:39'
 '05/07/2023 09:42:48' '05/07/2023 09:43:05' '05/07/2023 09:43:08'
 '05/07/2023 09:43:22' '05/07/2023 09:43:36' '05/07/2023 09:43:56'
 '05/07/2023 09:44:09' '05/07/2023 09:44:14' '05/07/2023 09:44:15'
 '05/07/2023 09:44:35' '05/07/2023 09:45:13' '05/07/2023 09:45:38'
 '05/07/2023 09:45:40' '05/07/2023 09:49:52' '05/07/2023 09:51:39'
 '05/07/2023 09:51:52' '05/07/2023 09:52:27' '05/07/2023 09:52:57'
 '05/07/2023 09:53:52' '05/07/2023 09:53:56' '05/07/2023 09:54:13'
 '05/07/2023 09:54:28' '05/07/2023 09:54:36' '05/07/2023 09:54:52'
 '05/07/2023 09:56:37' '05/07/2023 09:59:18' '05/07/2023 10:11:02'
 '05/07/2023 10:17:36' '05/07/2023 10:47:51']
What is your gender? -- ['Male' 'Marabou stock' 'Female ' 'Female' 'female' 'MALE' 'FEMALE' 'male'
 'Yes' 'M'] ------- ['Male' 'Marabou stock' 'Female ' 'Female' 'female' 'MALE' 'FEMALE' 'male'
 'Yes' 'M']
Age -- [21. 45. 20. 23. 22. 24. 25. 28. 19. nan 50. 30. 68. 29.] ------- [21. 45. 20. 23. 22. 24. 25. 28. 19. nan 50. 30. 68. 29.]
What is your emotion? -- ['Content' 'Weird' 'Happy' 'Happy ' 'irritated ' 'In a state of wonder'
 'Sad' 'happy' 'Moody' 'fine' 'TIRED FOR NOW' 'Jolly' 'Frustrated'
 'Anxious' 'HAPPY' 'calm' 'sad' 'Not sure' 'I hate nosense ' 'Joyful'
 'Nonchalant ' 'excited' 'stressed' 'Relaxed' 'Angry ' 'leaning'
 'Disgusted' 'Tired' 'Upset' 'Anger' 'angry' 'Sad ' 'Lonely' 'Happiness'
 'sleepy' 'tired' 'stress' 'unhappy' 'happy ' 'care' nan 'Afraid '
 'Scared' 'HAPPY ' 'Joy' 'Lonely ' 'panic' 'Hopeful' 'Fighting poverty'
 'good and bad' 'hunger' 'Grateful ' 'Yes'] ------- ['Content' 'Weird' 'Happy' 'Happy ' 'irritated ' 'In a state of wonder'
 'Sad' 'happy' 'Moody' 'fine' 'TIRED FOR NOW' 'Jolly' 'Frustrated'
 'Anxious' 'HAPPY' 'calm' 'sad' 'Not sure' 'I hate nosense ' 'Joyful'
 'Nonchalant ' 'excited' 'stressed' 'Relaxed' 'Angry ' 'leaning'
 'Disgusted' 'Tired' 'Upset' 'Anger' 'angry' 'Sad ' 'Lonely' 'Happiness'
 'sleepy' 'tired' 'stress' 'unhappy' 'happy ' 'care' nan 'Afraid '
 'Scared' 'HAPPY ' 'Joy' 'Lonely ' 'panic' 'Hopeful' 'Fighting poverty'
 'good and bad' 'hunger' 'Grateful ' 'Yes']
Year of birth -- ['2002' '2100' '2003' '2000' '2001' '1998' '1995' '2004' '1999' '2022'
 '1970' '18/11/1993' '5.10.2000' '10th/04/2001' '1st July 2002' '1953'
 '1994' '2023' '31/12/2001'] ------- ['2002' '2100' '2003' '2000' '2001' '1998' '1995' '2004' '1999' '2022'
 '1970' '18/11/1993' '5.10.2000' '10th/04/2001' '1st July 2002' '1953'
 '1994' '2023' '31/12/2001']
What is your CGPA? -- ['4.22' '8.9' '3.98' '4.37' '3.63' '3.8' '3.88' '3.79' '4.7' '4' '3.9'
 '3.56' '5' '3' '4.5' '4.68' '4.28' '3.76' '2.1' '3.7' '3.5' '4......'
 '3.6' '3.74' '3.67' '4.08' '4.16' '4.4' '4.6' '3.92' '3.87' '1.3' '4.65'
 '4.74' '4.03' '3.71' '4.1' '2.5' '2' '3.4' '4.26' '3.75' '4.2' '3.85'
 '3.1' '4.46' '3.18' '1' '3.66' '4.8' '4.9' '4.25' '4.52' '3.11' '4.83'
 '2.79' '3.3' '2.3' '3.78' "I don't know yet" '3.12' '2.88' '3.2'] ------- ['4.22' '8.9' '3.98' '4.37' '3.63' '3.8' '3.88' '3.79' '4.7' '4' '3.9'
 '3.56' '5' '3' '4.5' '4.68' '4.28' '3.76' '2.1' '3.7' '3.5' '4......'
 '3.6' '3.74' '3.67' '4.08' '4.16' '4.4' '4.6' '3.92' '3.87' '1.3' '4.65'
 '4.74' '4.03' '3.71' '4.1' '2.5' '2' '3.4' '4.26' '3.75' '4.2' '3.85'
 '3.1' '4.46' '3.18' '1' '3.66' '4.8' '4.9' '4.25' '4.52' '3.11' '4.83'
 '2.79' '3.3' '2.3' '3.78' "I don't know yet" '3.12' '2.88' '3.2']
Do you have a Girl Friend or BOY Friend -- ['No' 'Yes' 'no' 'Nope' 'yes' 'NO' 'YES' 'Yes ' 'Am a girl' 'Am a girl '
 'Sure, multiple girlfriends' 'Girl friends are thieves'
 'Namiiro Zahara Bidin' 'ARI'] ------- ['No' 'Yes' 'no' 'Nope' 'yes' 'NO' 'YES' 'Yes ' 'Am a girl' 'Am a girl '
 'Sure, multiple girlfriends' 'Girl friends are thieves'
 'Namiiro Zahara Bidin' 'ARI']
Do you have Depression? -- ['No' 'Yes' 'no' 'Nope' "don't know" 'NO' 'MAYBE' 'yes' 'Jo' 'none'
 'Probably' 'abit' 'NO '] ------- ['No' 'Yes' 'no' 'Nope' "don't know" 'NO' 'MAYBE' 'yes' 'Jo' 'none'
 'Probably' 'abit' 'NO ']
Do you have Anxiety? -- ['Yes' 'No' 'no' "I'm calm" 'yes' 'KINDA' 'YES' 'No ' 'none' 'Yes '
 'sometimes' 'Sometimes' 'not so ' 'swimming' 'Nope' 'NO' 'A little '
 'yeah'] ------- ['Yes' 'No' 'no' "I'm calm" 'yes' 'KINDA' 'YES' 'No ' 'none' 'Yes '
 'sometimes' 'Sometimes' 'not so ' 'swimming' 'Nope' 'NO' 'A little '
 'yeah']
Do you have Panic attack? -- ['Yes' 'No' 'yes ' 'Naaah' 'no' 'NO' 'yes' 'No ' 'none' 'YesNo' 'never'
 'Nope ' 'nah'] ------- ['Yes' 'No' 'yes ' 'Naaah' 'no' 'NO' 'yes' 'No ' 'none' 'YesNo' 'never'
 'Nope ' 'nah']
Did you have seek any specialist for a treatment?  -- ['Yes' 'No' 'Nope' 'yes' 'YES' 'NO' 'no' 'No ' 'yeah'] ------- ['Yes' 'No' 'Nope' 'yes' 'YES' 'NO' 'no' 'No ' 'yeah']

In [11]:
df2.duplicated().sum()

0